### ISSUE TITLE
Typo in jctl --help text for "-s, --searchpath"

### ISSUE THREAD

**Issue by eithor** [univ-of-utah-marriott-library-apple/jctl#27]
The help text for jctl searchpath (-s or --searchpath) has two typos '-p' instead of '-s' and a ',' instead of a '/'. The example given should be:

'-s general/id==152'

**Comment by magnusviri** [comment]
Where is this text? Is it the webpage or in the source code?

**Comment by eithor** [comment]
In the source code, currently line 119

**Comment by magnusviri** [comment]
I see, thanks. I've fixed it in my working copy and will commit it the next time I do a commit.

**Comment by magnusviri** [comment]
I've finally committed this and updated the release. Thanks for reporting it.
