### ISSUE TITLE
Inconsistent use of `-d` for deletion

### ISSUE THREAD

**Issue by homebysix** [univ-of-utah-marriott-library-apple/jctl#39]
Thanks for creating python-jamf and jctl. I think these projects may be something I can build on for my organization.

I did notice that `jctl -d` deletes an object, while `pkgctl -d` sets patch definitions. Is it too late to make `-d` mean the same thing across both tools? The inconsistency increases the likelihood that somebody might inadvertently delete an object by calling the wrong tool (although the risk is lessened by the confirmation prompt).

Thanks for considering!

**Comment by uurazzle** [comment]
Hi Elliot:

Thanks for the feedback and suggestion it sounds like a good idea. We will make the usage the same across tools and let you know status.
I think these projects may be something I can build on for my organization.
Is their interest in contributing to the project? If there is, we meet weekly on Wed, 3-5 PM MT and have a private channel for development discussions. Let us know if you are interested.

Thanks,

Richard Glaser (he,his, him)
University of Utah, Marriott Library
On Nov 27, 2021, 6:04 PM -0700, Elliot Jordan ***@***.***>, wrote:

Thanks for creating python-jamf and jctl. I think these projects may be something I can build on for my organization.

I did notice that jctl -d deletes an object, while pkgctl -d sets patch definitions. Is it too late to make -d mean the same thing across both tools? The inconsistency increases the likelihood that somebody might inadvertently delete an object by calling the wrong tool (although the risk is lessened by the confirmation prompt).

Thanks for considering!

**Comment by homebysix** [comment]
Sure, I can't commit too much time but I'd be happy to poke my head in now and then.

**Comment by magnusviri** [comment]
I just fixed this [#43](https://github.com/univ-of-utah-marriott-library-apple/jctl/pull/43)
