### ISSUE TITLE
"Couldnt Save Changed Record"

### ISSUE THREAD

**Issue by jtkear16** [univ-of-utah-marriott-library-apple/jctl#51]
![image (20)](https://user-images.githubusercontent.com/9383041/189991146-4932e737-e77f-4c98-bdb1-510eaea6aeea.png)

Get a weird error when trying to change the category for a mobile device app. Looks like a translation issue that is getting Latin-1 when expecting UTF-8. 
App Name: Adobe Photoshop
Bundle ID: com.adobe.photoshop.ios
Category Name: Applications

Issue persistent in Terminal and CodeRunner text editor where default setting is UTF-8.

**Comment by magnusviri** [comment]
@jtkear16, we've added a "--debug" option that displays the XML sent to the server and the XML returned. Can you try the new version and let us know if it's still happening?

**Comment by magnusviri** [comment]
I have a fix for this. I don’t know when I’ll have time to do a release with the fix.

**Comment by magnusviri** [comment]
Sorry for taking so long to release the fix. It is out now.

**Comment by jtkear16** [comment]
Confirmed I'm able to do what I couldnt before. Thank you!
