### ISSUE TITLE
Variable not set before use in jctl 1.1.19

### ISSUE THREAD

**Issue by eithor** [univ-of-utah-marriott-library-apple/jctl#57]
For jctl 1.1.19 with python-jamf 0.8.3 (but works with jctl 1.1.18 and the same python-jamf):

jctl patchsoftwaretitles -r Something -S set_all_packages

...
Count: 2
Traceback (most recent call last):
  File "/Users/macautopkg/JCTL/jctl-git/jctl/./jctl", line 692, in <module>
    main(sys.argv[1:])
  File "/Users/macautopkg/JCTL/jctl-git/jctl/./jctl", line 621, in main
    confirmed = change_confirmation(args, rec_class, filtered_results)
  File "/Users/macautopkg/JCTL/jctl-git/jctl/./jctl", line 475, in change_confirmation
    f"Are you sure you want to {change_type_} "
UnboundLocalError: local variable 'change_type_' referenced before assignment

**Comment by uurazzle** [comment]
Hi @eithor:

Thanks for filing a problem ticket. We will troubleshoot and let you know the status as soon as we have the bandwidth and are able to focus on it.

**Comment by magnusviri** [comment]
I've fixed this bug in the main branch. I don't know exactly when I'll release a new version. I could releases a new version sooner if you really need this feature. You can do the same thing with `pkgctl -p`.
